# PostGreSQL 
# gem install pg

development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: rrix
  password: hsmderp
  database: hsm_development
  schema_search_path: public
  encoding: utf8
  template: template0
  
test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: rrix
  password: hsmderp
  database: hsm_test
  schema_search_path: public
  encoding: utf8
  template: template0
  
production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: rrix
  password: hsmderp
  database: hsm_production
  schema_search_path: public
  encoding: utf8
  template: template0